name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c9a2bb760bd78c9ed74f068d14df537d4c3537f010ac5cdeec04be1d0a95993"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
