name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d4b46378559d968290ad64ce033545781386954c872c30af9b933b2a6c1a7f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
