name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "166ecd0ced1e842408fa077635cb7c7fcb962d598c38776550bfdab42211453d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
