name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5956267f6abfecc9d199a791134ba7e787b975453d290ee701d8f08f8f6adc64"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
