name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d741262281c7ea98dc4e82bb9e7cc397ec65811c9515e01fc9290e97b34174db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
