name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51a9b69aba0bc17a845242c3d4d0ccf732169a03fa6756255a47a2697d04fdc2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
