name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd75758d53bbc4719bf1d46b1fd68339b49b66e73947475d4b9322dd78a2bc27"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
