name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d65245bfe2aa6a9bd00efe7acc8d3e28b7756a5c76bb2b911324da1001e43af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
