name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0d4bb51d2f4e53b4205f59dae2d6497e1483ba881085cae0b424b8c4a55bc0a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
