name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28fc4c517d6de89523d686f3af5cdc3f87087bec6903d7b6b2f93a1b7f408d28"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
