name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a7126a872aff5e28532179507ee663ffb710d21c725b7ac784efb021866fc0f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
