name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36c5042dc241ad9b0054c3fd62d9e5466e16248ec0bcab8ae137192ed29d4514"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
