name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1ec8aa3aa64e24c7236eccfada23748f361ee6c080095d325c86e5f5c7d68c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
