name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7804e2842637dbcf7bd6a8533cef7d4e928259ae69172cd8ce029dce3201ab08"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
