name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a62b882e8f0e3b9a72291debee239bbad90868962b59ef623d71f1016371a738"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
