name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb08c9a0ba713150ebbbf6a95f326678411fbe51aa2c36b4f35e0c0d3963921e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
