name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f072afc367e515f0029753aeb207ef544a556749cbf6a7b36dd932038449e1cb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
