name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e4035126ee36aa349ae767d39640303b539ab6ffbbe50bf74a3c004abc86844"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
