name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a1247fe6bb32e20d975327a96040c667c81d377fd709590c657261639a9e60e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
