name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f84b1185b15c822e57d4cf3c4b56afe7d83716bc291fef60ebb14712a1abe86"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
