name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65ecc79956e66548bcc7ef33d0ff4c3ae811b1bbf497a677709645e37a8d46e9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
