name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c25f6b5a4f6f2905f243929bc42dae53b033d2577f8d62539ccaad3361f7879b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
