name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69fc29f73f5033d5bab3aedf02838d3593b75d1edb3c924d4599af57a5a9de3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
