name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e500bb04aaf76e3c86248f0025adab481a54f53cede354272955fd95ba16425"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
