name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "620022d7816efdbbdb2fa82a26b3e94399f50f3e4bd5eb486f02e87321829a2d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
