name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ceb509c58245c30d33bacc2402a179d295a8b11e5bc03fff2dff8a1c5ece1a98"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
