name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91179e5173396ec8970b9674c7654f9d7e3f6e68bb6864c417162258c99ea6a6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
