name = "kookykraft-neo"
author = "izmystic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a32f3afadca4a943afe63e261df27d01005f76a66fbb17ecf0278b55655c7f35"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
